// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocalsynthDatabaseWebsite.Data;

#nullable disable

namespace VocalsynthDatabaseWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506202045_AddSongProducerEntities")]
    partial class AddSongProducerEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.SongProducer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProducerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProducerId");

                    b.HasIndex("SongId");

                    b.ToTable("SongProducers");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.SongVocalSynth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocalSynthEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("VocalSynthEntryId");

                    b.ToTable("SongVocalSynths");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.VocalSynthEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceBank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VocalSynthEntries");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.SongProducer", b =>
                {
                    b.HasOne("VocalsynthDatabaseWebsite.Models.Producer", "Producer")
                        .WithMany("SongProducers")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocalsynthDatabaseWebsite.Models.Song", "Song")
                        .WithMany("SongProducers")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.SongVocalSynth", b =>
                {
                    b.HasOne("VocalsynthDatabaseWebsite.Models.Song", "Song")
                        .WithMany("SongVocalSynths")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocalsynthDatabaseWebsite.Models.VocalSynthEntry", "VocalSynthEntry")
                        .WithMany("SongVocalSynths")
                        .HasForeignKey("VocalSynthEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("VocalSynthEntry");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.Producer", b =>
                {
                    b.Navigation("SongProducers");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.Song", b =>
                {
                    b.Navigation("SongProducers");

                    b.Navigation("SongVocalSynths");
                });

            modelBuilder.Entity("VocalsynthDatabaseWebsite.Models.VocalSynthEntry", b =>
                {
                    b.Navigation("SongVocalSynths");
                });
#pragma warning restore 612, 618
        }
    }
}
